name = "LES_ML"
uuid = "9bca47e3-315e-42b6-a9a0-21ad79062dce"
authors = ["tobyvg <tobyvangastelen@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
